# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./DB/data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    networks:
      - ruby-api-network

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongo:27017/
    depends_on:
      - mongo
    networks:
      - ruby-api-network
  
  ruby-api-app:
    image: iglesias9627/ruby_api_sinatra:v0.0.2
    restart: always
    ports:
      - 4567:4567
    environment:
      RACK_ENV: production
    networks:
      - ruby-api-network
  
  nodejs-fetch-module:
    image: iglesias9627/node_js_fetching_module:v0.0.1
    restart: always
    environment:
      MONGODB_URI: 'mongodb://admin:admin@mongo:27017/admin'
      TIME_CRON: '50 18 * * *'
      LOGGER_DIR: logs
    depends_on:
      - mongo
    volumes:
      - ./logs:/app/src/logs
    networks:
      - ruby-api-network

networks:
  ruby-api-network: