development:
  clients:
    default:
      database: admin
      hosts:
        - localhost:27017
      options:
        server_selection_timeout: 1
        user: admin
        password: admin

production:
  clients:
    default:
      database: admin
      hosts:
        - mongo:27017
      options:
        server_selection_timeout: 1
        user: admin
        password: admin